language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

## Reference link
## https://ethereum.stackexchange.com/a/42658
script:
  - npm install
  - ng build --prod --aot