language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g truffle
  - npm install -g @angular/cli

script:
  - cd angular && ng build --prod --aot
  - cd ../ethereum && truffle test