language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    
cache:
  directories:
    - "node_modules"    

before_script:
  - npm install -g @angular/cli

## Reference link
## https://ethereum.stackexchange.com/a/42658
script:
  - npm install