language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install -g @angular/cli

## Reference link
## https://ethereum.stackexchange.com/a/42658
script:
  - cd angular && npm install
  - ng build --prod --aot
  - cd ../ethereum
  - ganache-cli -p 7545 > /dev/null &
  - sleep 5
  - truffle migrate 
  - truffle test